name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Build and install
      run: |
        python -m pip install pytest pytest-benchmark scipy
        pip install --verbose .

    - name: Test
      run: python -m pytest
